import styled from "styled-components";
import { BtnBack } from "../components/button";
import Head from "next/head";
const Container = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: black;
  @media (max-width:700px){
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }
  h1 {
    color: rgb(126, 217, 87);
    text-align: center;
    padding-top: 0.6rem;
    font-size: 3rem;
    @media (max-width:700px){
        font-size: 2rem;
        padding-top: 1rem;
    }
  }
  p {
    width:25rem;
    height: 19rem;
    color: white;
    font-size: 1.2rem;
    @media (max-width:850px){
        font-size: 1rem;
    }
    @media (max-width:700px){
        font-size: 0.8rem;
        padding: 10px;
    }
  }
  div {
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  img{
    @media (max-width:700px){
    display:none;
  }
  }
`;
const About = () => {
  return (
    <Container>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Rancho&display=swap');
        </style>
        <title>Sobre</title>
      </Head>
      <h1>Minha Jornada</h1>
      <div>
        <p>
          Em Novembro de 2021 iniciei meu processo de transição de carreira,
          desde então tenho me dedicado ao máximo para evoluir as hards e softs
          skills que me qualifiquem para iniciar minha carreira como
          desenvolvedor. Tenho sólidos conhecimentos em javascript para o
          front-end, tenho experiência em construções de spa, usando nextJs
          junto ao React, conhecimento de ferramentas que auxiliam na
          estilização como styled-components e tailwind css, conhecimentos da
          arquitetura flux do react e tambem do context api. Do ponto de vista
          das softs skills, considero me alguem que tem muita facilidade para
          trabalhar em equipe que consegue conversar com todas as partes
          envolvidas e que deixa o ego bem longe no momento de desenvolver algo
          em grupo, tenho um apetite em conhecer sobre novos assuntos e
          tecnologias, e que absorve com certa rapidez.
        </p>
        <img src="/percoffe.png" alt="animaçao lucas" />
      </div>
      <BtnBack />
    </Container>
  );
};
export default About;
