import styled from 'styled-components'
import React, { useRef } from 'react';
import { BsLinkedin, BsWhatsapp, BsGithub } from 'react-icons/bs';
import { BtnBack } from '../components/button';
import Head from 'next/head'
import emailjs from '@emailjs/browser';

const Container = styled.div`
width:100vw;
height:100vh;
background-color:black;
display:flex;
justify-content: center;
align-items: center;
flex-direction: column;

label{
  color:black;
}
h1{
  color:rgb(126,217,87);
  margin-bottom: 10px;
}
form{
  height: 400px;
  width: 300px;
  border:1px solid white;
  display: flex;
  flex-direction: column;
  background-color: white;
  border-radius: 8px;
  padding: 10px;
  
}
span{
  color:red;
}
input{
  height: 40px;
  margin-top: 5px;
  margin-bottom: 5px; 
  border:1px solid rgb(126,217,87);
  border-radius: 4px;
}
.textarea{
  height: 200px;
}
button{
  background-color: transparent;
  border:1px solid black;
  padding:10px;
  border-radius:8px;
}
`
const BoxContent = styled.div`
  display:flex; 
  @media (max-width:380px){
    flex-direction: column;
  }
`
const Icons = styled.div`
  display:flex;
  flex-direction: column;
  margin-right:10px;
  gap:5px;
  .icon{
  color:white;
  background-color:rgb(126,217,87);
  font-size:4rem;
  border-radius: 16px;
  cursor:pointer;
}
@media (max-width:380px){
  flex-direction:row;  
  order:2;
  justify-content: space-between;
  margin:10px;
  }
`
const Contacts = () => {

  const sendEmail = (e) => {
    e.preventDefault();
   
    emailjs.sendForm('service_y7nbgox', 'template_3yqutlf', e.target, 'F2-hqlHDf85rde1Pz')
      .then((result) => {
          alert("Messagem enviada, obrigado pelo contato")
      }, (error) => {
          alert("Ops sua mensagem não foi enviada")
      });
      e.target.reset()
  }
  return(
    <Container>
       <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Rancho&display=swap');
        </style>
        <title>Contatos</title>
      </Head>
      <h1>Contatos</h1>
      <BoxContent>
      <Icons>
      <a
          href="https://www.linkedin.com/in/devklucas/"
          target="https://www.linkedin.com/in/devklucas/"
        ><BsLinkedin className='icon'></BsLinkedin></a> 
       <a href="https://wa.link/336jfw" target="_blank">
       <BsWhatsapp className='icon'></BsWhatsapp>
       </a>
      <a
          href="https://github.com/devklucas"
          target="https://github.com/devklucas"
        >
      <BsGithub className='icon'></BsGithub>
      </a>
      </Icons> 
      <form onSubmit={sendEmail}>
      <label>Nome: <span>*</span></label>
      <input type="text" name="name" placeholder='Insira seu nome' />
      <label>Email: <span>*</span></label>
      <input type="email" name="email" placeholder='Insira seu email'/>
      <label>Messagem: <span>*</span></label>
      <input type="text" className='textarea' name="message" placeholder='Escreva sua mensagem...'/>
      <button type="submit" >Enviar</button>
      </form>
    </BoxContent>
    <BtnBack></BtnBack>
    </Container>
    )
}
export default Contacts
