import { useState } from "react";
import { FcMenu } from "react-icons/fc";

import Head from "next/head";
import Link from "next/link";

import {
  Container,
  SideImage,
  SideButtons,
  ContentButtons,
  ContentLink,
  MenuMobile,
} from "../components/sharedstyles";

export default function Home() {
  const [mobileMenu, setMobileMenu] = useState(false);
  const handleMenu = () => {
    setMobileMenu(!mobileMenu);
    setTimeout(() => {
      setMobileMenu(false);
    }, 5000);
  };
  return (
    <Container>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Rancho&display=swap');
        </style>
        <title>Devklucas</title>
      </Head>
      <SideImage>
        <img src="/hello.png" alt="lucas" />
      </SideImage>
      <SideButtons>
        <ContentButtons>
          <div>
            {mobileMenu === false ? (
              <FcMenu className="icon" onClick={handleMenu}></FcMenu>
            ) : (
              <MenuMobile>
                <p onClick={handleMenu}>X</p>
                <Link href="/works">Trabalhos</Link>
                <Link href="/contacts">Contatos</Link>
                <Link href="/about">Sobre</Link>
              </MenuMobile>
            )}
            <a
              className="download"
              href="/curriculum.pdf"
              download="curriculum"
            >
              Baixar cv
            </a>
            <Link href="/works">
              <button>Trabalhos</button>
            </Link>
            <Link href="/contacts">
              <button>Contatos</button>
            </Link>
            <Link href="/about">
              <button>Sobre</button>
            </Link>
          </div>
          <h1>// Front-end React // devklucas </h1>
        </ContentButtons>
        <ContentLink>
          <span>Olá sou o Lucas</span>
          <Link href="/contacts">
            <img src="/workwithme.gif" alt="arte" />
          </Link>
        </ContentLink>
      </SideButtons>
    </Container>
  );
}
