import styled from "styled-components";
import { BtnBack } from "../components/button";
import Cards from "../components/cards";
import Head from "next/head";
interface worksprops {
  id: number;
  name: string;
  img: string;
  description: string;
  demo: string;
  repositorio: string;
}

const Container = styled.div`
  background-color: black;
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: space-evenly;
  align-items: center;
  flex-direction: column;
  h1 {
    padding-top:10px;
    width: 100%;
    color: rgb(126, 217, 87);
    font-size: 1.9rem;
    text-align: center;
  }
  @media(max-width:1024px){
    height: auto;
    h1{
      padding-top:60px;
      font-size: 1.2rem;
    }
  }
`;
const BoxImages = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  width: 90%;
  @media(max-width:1024px){
    flex-direction: column;
    height:auto;
    gap:10px;
  }
`;

export default function Works() {
  const works: Array<worksprops> = [
    {
      id: 1,
      name: "Controle de gastos",
      img: "/work3.gif",
      description: `Gerenciador de gastos simples, onde você pode adicionar entradas e saídas e controlar suas economias`,
      demo: "https://manager-wallet.vercel.app/",
      repositorio: "https://github.com/devklucas/manager_wallet",
    },
    {
      id: 2,
      name: "Eccomerce",
      img: "/work2.gif",
      description: `Um exemplo de um eccomerce para restaurante que pode ser
      facilmente escalado com a construção de um api e novas features,
      teste a aplicação`,
      demo: "https://hamburgueria-kenzie-snowy-theta.vercel.app/",
      repositorio: "https://github.com/devklucas/hamburgueria_kenzie",
    },
    {
      id: 3,
      name: "Rick and Morty",
      img: "/work1.gif",
      description:
        "Para quem é fã de rick and Morty essa aplicação trás todos personagem da animação e mostra algumas informações dos mesmos",
      demo: "https://rick-and-morty-psi-cyan.vercel.app/",
      repositorio: "https://github.com/devklucas/rick_and_morty",
    },
  ];
  return (
    <Container>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Rancho&display=swap');
        </style>
        <title>Meus trabalhos</title>
      </Head>
      <h1>PRINCIPAIS TRABALHOS</h1>
      <BoxImages>
        {works.map((work) => (
          <Cards work={work} key={work.id} />
        ))}
        <BtnBack />
      </BoxImages>
    </Container>
  );
}
